name: Django CI/CD Pipeline for Linode

on:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Linode
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@139.162.134.90 << 'EOF'
          cd /
          git pull origin main
          source /venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_KEY }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LINODE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
