services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gogrok-backend-app
    image: gogrok-backend-app  # Explicitly set the image name
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/gogrok/logs
      - .:/gogrok
      - /gogrok/staticfiles
      

    environment:
      - REDIS_URL=redis://redis:6379/1  # Docker service name
    depends_on:
      - redis
    command: >
      sh -c "
      mkdir -p /gogrok/logs &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 config.wsgi:application
      "

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  logs: