version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gogrok-backend-app
    image: gogrok-backend-app
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./logs:/root/gogrok/logs 
      - .:/gogrok
      - ./staticfiles:/gogrok/staticfiles
    environment:
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
    command: >
      sh -c "
      mkdir -p /gogrok/logs &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8001 config.asgi:application &
      gunicorn --bind 0.0.0.0:8000 config.wsgi:application --log-level debug
      "
    mem_limit: 1g
    mem_reservation: 512m

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  logs:
  staticfiles:
