# Generated by Django 5.1.2 on 2024-12-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("task", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionStatisticsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("total_competitions", models.IntegerField(default=0)),
                ("tasks", models.ManyToManyField(to="task.task")),
            ],
        ),
    ]
