# Generated by Django 5.0.2 on 2024-11-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_alter_competition_duration_minutes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
