# Generated by Django 5.1.2 on 2024-12-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.JSONField()),
                ("output", models.JSONField()),
                ("input_type", models.JSONField()),
                ("output_type", models.JSONField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="task.task",
                    ),
                ),
            ],
        ),
    ]
