# Generated by Django 5.1.2 on 2024-10-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0002_alter_testcase_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_type',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_type',
            field=models.JSONField(),
        ),
    ]
