# Generated by Django 5.1.2 on 2024-10-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0003_alter_testcase_input_alter_testcase_input_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
