# Generated by Django 5.1.2 on 2024-10-30 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0005_task_description'),
        ('test_case', '0004_delete_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.JSONField()),
                ('output', models.JSONField()),
                ('input_type', models.JSONField()),
                ('output_type', models.JSONField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_cases', to='task.task')),
            ],
        ),
    ]
