# Generated by Django 5.1.2 on 2024-11-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_description'),
        ('test_case', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='task.task'),
        ),
    ]
