name: Django CI/CD Pipeline for Linode

on: 
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint  # Install Pylint for code quality checks

      - name: Run Pylint
        run: |
          pylint $(find . -name "*.py") # Lint all Python files in the repository


      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LINODE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 139.162.134.90 >> ~/.ssh/known_hosts

      - name: Deploy to Linode with Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@139.162.134.90 << 'EOF'
          cd /
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          EOF
        
      - name: Debug Docker Compose logs
        if: failure()
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@139.162.134.90 << 'EOF'
          cd /
          docker-compose logs
          EOF
