name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python, pip, and Linode CLI
      - name: Install Python, pip, and Linode CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install linode-cli
          linode-cli --version  # Verify installation

      # Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # SSH into the server and create the Hello.txt file
      - name: Create Hello.txt on Linode server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@139.162.134.90 "mkdir -p /root/gogrok && echo 'Hello, world!' > /root/gogrok/Hello.txt"

  linode-verify:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Install Linode CLI (if necessary)
      - name: Install Linode CLI
        run: |
          sudo apt-get update
          sudo pip3 install linode-cli

      # Run Linode CLI command with the correct environment variable
      - name: Run Linode CLI command
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }}  # Linode Personal Access Token
        run: |
          linode-cli linodes ls
