name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Docker and Docker Compose
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

      # Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # Set up Linode CLI (if needed)
      - name: Install Python, pip, and Linode CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install linode-cli

      # Configure Linode CLI
      - name: Configure Linode CLI (Non-Interactive)
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
        run: |
          mkdir -p ~/.config/linode-cli
          echo "[DEFAULT]" > ~/.config/linode-cli/config
          echo "token = $LINODE_TOKEN" >> ~/.config/linode-cli/config

  docker-build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Checkout the code again
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker and Docker Compose again (as separate job)
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

      # Build and run Docker Compose
      - name: Build and start Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # Wait for containers to stabilize
      - name: Wait for containers
        run: |
          sleep 20  # Adjust time based on your container startup time

      # Optionally, you can add tests or other commands here after the containers start
      - name: Run tests or other tasks
        run: |
          docker exec -it <container_name> <test_command>  # Run any tests inside a container

      # Tear down Docker containers (optional)
      - name: Tear down Docker containers
        run: |
          docker-compose -f docker-compose.yml down
