name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH to your server
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 139.162.134.90 >> ~/.ssh/known_hosts  # Replace with your server's IP

      # Configure Linode CLI (Non-Interactive)
      - name: Configure Linode CLI (Non-Interactive)
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
        run: |
          mkdir -p ~/.config/linode-cli
          echo "[DEFAULT]" > ~/.config/linode-cli/config
          echo "token = $LINODE_TOKEN" >> ~/.config/linode-cli/config

  docker-build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Checkout the code again
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image and run container remotely
      - name: Build Docker image and run container remotely
        run: |
          ssh -o StrictHostKeyChecking=no user@139.162.134.90 "
            cd /root/gogrok && \
            sudo docker build -t gogrok . && \
            sudo docker run -d --name gogrok gogrok"
        
      # Wait for container to stabilize
      - name: Wait for container
        run: |
          sleep 20  # Adjust time based on your container startup time

      # Optional: Stop and remove the container
      - name: Stop and remove container remotely
        run: |
          ssh -o StrictHostKeyChecking=no root@139.162.134.90 "sudo docker stop gogrok && sudo docker rm gogrok"
