name: Django CI/CD Pipeline for Linode

on: 
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LINODE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 139.162.134.90 >> ~/.ssh/known_hosts

      - name: Deploy to Linode with Docker Compose
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@139.162.134.90 << 'EOF'
          cd /gogrok
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          EOF
        
      - name: Debug Docker Compose logs
        if: failure()
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@139.162.134.90 << 'EOF'
          cd /gogrok
          docker-compose logs
          EOF
