name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python, pip, and Linode CLI
      - name: Install Python, pip, and Linode CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --user linode-cli
          echo "$(which linode-cli)"
          # Add user bin path to PATH
          echo "PATH=$PATH:~/.local/bin" >> $GITHUB_ENV

      # Set up SSH for Lish access
      - name: Set up SSH for Lish access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa lish-eu-central.linode.com >> ~/.ssh/known_hosts  # Lish domain
          
      - name: Debug SSH connection (with more details)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa lish-eu-central.linode.com >> ~/.ssh/known_hosts  # Lish domain
          ssh -v -o StrictHostKeyChecking=no feruzbek23@lish-eu-central.linode.com "echo SSH connected"


  # Optional: Run Docker build and container
  docker-setup:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Docker image and run container
        run: |
          docker build -t gogrok /root/gogrok
          docker run --name gogrok -d gogrok
