name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install linode-cli
          linode-cli --version  # Verify installation

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Run Docker Compose on Linode
        run: |
          ssh -o StrictHostKeyChecking=no root@139.162.134.90 << 'EOF'
            # Navigate to the /root/gogrok directory
            cd /root/gogrok
            # Pull changes
            git pull origin main
            # Run Docker Compose to start the containers
            docker-compose down --volumes
            docker-compose up -d --build
          EOF

  linode-verify:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Install Linode CLI
        run: |
          sudo apt-get update
          sudo pip3 install linode-cli

      - name: Run Linode CLI command
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }} 
        run: |
          linode-cli linodes ls
